@startuml Calculation

title From history.csv to report and totals
!pragma useVerticalIf off

start
    :Build ReportRows from transaction history CSV rows:
      -FUNDING_WITHDRAWAL
      -TRADE (buy/sell/exchange)
      -COMMISSION
      -DIVIDEND
      -TAX
      -AUTOCONVERSION
      -CORPORATE_ACTION;

    :Build TransactionItems from ReportRows:
      -funding
      -withdrawal
      -buy
      -sell
      -exchange
      -dividend (likely with tax)
      -tax (likely from dividend, but reported later in time)
      -autoconversion
      -corporateaction;
 
    :Match Buy and Sell items into BuySellPairs, in FIFO manner, 
    remembering amount of asset sold per each pair;

    :Quote in PLN (previous working day scheme):
      -BuySellPairs -> BuySellPairsPLN
      -DividendItems -> DividendItemsPLN
      -TaxItems -> TaxItemsPLN;

    :Build Profits (received - paid) from BuySellPairsPLN,
     based on amount_sold;

    :Build report from Profits, Dividends and Taxes,
      grouped by asset;
stop
@enduml